language: cpp
matrix:
  include:
  - compiler: gcc
    os: linux
  - compiler: clang
    os: osx
dist: xenial
addons:
  homebrew:
    packages:
    - eigen
    - qt
    update: true
  apt:
    packages:
    - qt5-default
    - libeigen3-dev
script:
- cmake . && make
deploy:
  on:
    branch: master
    tags: true
    condition: $TRAVIS_OS_NAME = "linux"
  provider: pypi
  user: koyama
  password:
    secure: Vt5Qoh6te86anS0W0FqJEy8K1brRTzO7Mh1vKAXqVDwbaWIRRQoHlrpR8nIaV9tXC8wNUHeF80uNk+bDeqzoeGwZbIzYFS6V44+BC+oUTs0wKW7zETaB1M/uMZeNol++HSs7ajFsI+2KnQ5Gw50XVVohypTNxFOz5HXDMVa2c4HdVDku4gyZ3IMd0iRbkYBBA2FXvCzLEN7zid2r98Q4BTWBLUulx3AWrBiflQ8i35iJDdDdIzxZUMOkIFSjPGMkb66a1C4RCgO3l8x3TkEAOHwrYmycbL185w0g0mjhOO2Eia3d/9BmpHuEUBZJ+ihKDpWZMHIChvoea11Dj90pnaMYi9vHqmAjNa1oM0bkYTHsDDmau5RDwfQf7cHttn6aRy6M7Vq2WdlZLzdtWqtCGcSlrhLDSLHY5csSkTS4q2251qcnVgIEgeo1JMFNpj2hbQYIqo0iWnfJaBeslA8H5io71/+zdoXTTgsLGlVOcSApnwfyTLySfloJadr5X6msTXyUq/NjU/RCcsmjfusbKg7hh0jSXOkE0u5bd8K4HMKH0M+B0IxSVBvz6z8tCch4vcn9EldV20Zgr/G25z/i7xW2eSZIBJB0nOqUEFBhxdsaGtPaH/G80RXvMHPnYBfb67mPkbC9JBEdGUVtxGo9+GvbVQyddRk8WIsmEn3zHUw=
  distributions: sdist bdist_wheel
  skip_existing: true
