# Build the c++ library
language: cpp
matrix:
  include:
    - compiler: gcc
      os: linux
    - compiler: clang
      os: osx
dist: xenial
addons:
  homebrew:
    packages:
    - eigen
    - qt
    update: true
  apt:
    packages:
    - qt5-default
    - libeigen3-dev
script:
- cmake . && make
